<!doctype html>

<html lang="es" style="margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;height:100%;" >
  <head style="margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;" >
    <meta name="theme-color" content="#ffffff" style="margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;" >
    <meta charset="utf-8" style="margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;" >
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0" style="margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;" >
    <title style="margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;" >Mailing</title>
    <meta name="description" content="Mailing template" style="margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;" >
    <meta name="author" content="2Geeks one Monkey" style="margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;" >
  <style style="margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;" >
    @import url("https://fonts.googleapis.com/css?family=Open+Sans:300,400,700,800");*,*:after,*:before{box-sizing:border-box}*{margin:0;padding:0}body{background-color:#fff;font-family:"Open Sans",sans-serif;font-size:16px;font-weight:300;color:#959595;position:relative}a{color:#3F5BCA;font-family:"Open Sans",sans-serif;font-size:16px;font-weight:400;text-decoration:none}p{text-align:left}h1,h2,h3,h4,h5,h6,.h1,.h2,.h3,.h4,.h5,.h6{font-family:"Open Sans",sans-serif;font-weight:300;letter-spacing:1px;margin:0;padding:0;color:#292929;text-align:left;margin-bottom:.5em}h1,.h1{font-size:2.8em}h2,.h2{font-size:1.5em}@media screen and (max-width: 480px){h2,.h2{font-size:1.4em}}h3,.h3{font-size:2em}h4,.h4{font-size:1.6em}@media screen and (max-width: 320px){h4,.h4{font-size:1.1em;font-size:1.1em}}h5,.h5{font-size:1.4em}h6,.h6{font-size:.7em}hr{border:none;margin:0}.wrap{position:relative}input{height:45px;width:85%;text-align:right;font-size:2em;font-weight:700;letter-spacing:1px;border-radius:3px;border-style:solid;border-color:#3F5BCA}input::placeholder{color:#576fd1}input:focus,input:active{outline:none}.btn{-moz-user-select:none;-ms-user-select:none;-webkit-user-select:none;border-radius:.25rem;border:1px solid transparent;cursor:pointer;display:inline-block;font-family:"Open Sans",sans-serif;font-size:1.04rem;font-weight:400;line-height:1.25;padding:.6rem 1.2rem;text-align:center;user-select:none;vertical-align:middle;white-space:nowrap;margin:2em auto;-webkit-border-radius:4px;-moz-border-radius:4px;-ms-border-radius:4px;border-radius:4px;box-shadow:0 3px 0 rgba(0,0,0,0.05);min-width:100px;color:#fff}.btn.active.focus,.btn.active:focus,.btn.focus,.btn:active.focus,.btn:active:focus,.btn:focus{outline:none;outline-offset:-2px}.btn:focus,.btn:hover{text-decoration:none;color:#fff}.btn.focus{text-decoration:none}.btn.active,.btn:active{background-image:none;outline:0}.btn-primary{color:#fff;background-color:#3F5BCA;border:none}.btn-primary:hover{color:#fff;background-color:#3F5BCA;border:none}.btn-full{width:100%}.container{height:100%}.container-mailing{max-width:500px;width:500px;height:auto;margin:130px auto 32px;background-color:#fff;padding:32px;padding-bottom:16px;-webkit-box-shadow:0 2px 14px 0 rgba(0,0,0,0.12);-moz-box-shadow:0 2px 14px 0 rgba(0,0,0,0.12);box-shadow:0 2px 14px 0 rgba(0,0,0,0.12);-webkit-border-radius:7px;-moz-border-radius:7px;-ms-border-radius:7px;border-radius:7px}html{height:100%}body{background-color:#F3FBFF;overflow:hidden;height:100%;background-image:-webkit-linear-gradient(44deg, #89F7FE 0%, #66A6FF 100%);background-image:-o-linear-gradient(44deg, #89F7FE 0%, #66A6FF 100%);background-image:linear-gradient(134deg, #89F7FE 0%, #66A6FF 100%);text-align:center}h2{font-weight:700}.logo{text-align:center;margin:0 auto 32px;width:80px}.footer-logo{width:40px}.footer h6{text-align:center;margin-bottom:1.5em;color:#fff}.disclaimer{font-size:.6em;text-align:justify;margin-bottom:10px}
  </style>
  </head>

  <body style="margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;font-family:'Open Sans',sans-serif;font-size:16px;font-weight:300;color:#959595;position:relative;background-color:#F3FBFF;overflow:hidden;height:100%;background-image:linear-gradient(134deg, #89F7FE 0%, #66A6FF 100%);text-align:center;" >
    
    <div class="container container-mailing" style="max-width:500px;width:500px;height:auto;margin-top:130px;margin-bottom:32px;margin-right:auto;margin-left:auto;background-color:#fff;padding-top:32px;padding-bottom:16px;padding-right:32px;padding-left:32px;-webkit-box-shadow:0 2px 14px 0 rgba(0,0,0,0.12);-moz-box-shadow:0 2px 14px 0 rgba(0,0,0,0.12);box-shadow:0 2px 14px 0 rgba(0,0,0,0.12);-webkit-border-radius:7px;-moz-border-radius:7px;-ms-border-radius:7px;border-radius:7px;" >
      <img class="logo" src="https://qa.2geeksonemonkey.com/mailings/licuadora/images/logo.png" alt="" style="padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;text-align:center;margin-top:0;margin-bottom:32px;margin-right:auto;margin-left:auto;width:80px;" >
      <h2 style="font-family:'Open Sans',sans-serif;letter-spacing:1px;margin-top:0;margin-bottom:.5em;margin-right:0;margin-left:0;padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;color:#292929;text-align:left;font-size:1.5em;font-weight:700;" >
        Hola <?= $nombre ?>
      </h2>
      <p style="margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;text-align:left;" >
        Te invitamos a realizar las evaluaciones de desempeño de tus compañeros, colaboradores (si aplica), y la tuya dando click en el siguiente bóton
      </p>
      <a class="btn btn-primary btn-full" href="<?= $url ?>" style="text-decoration:none;-moz-user-select:none;-ms-user-select:none;-webkit-user-select:none;border-radius:4px;border-width:1px;border-color:transparent;cursor:pointer;display:inline-block;font-family:'Open Sans',sans-serif;font-size:1.04rem;font-weight:400;line-height:1.25;padding-top:.6rem;padding-bottom:.6rem;padding-right:1.2rem;padding-left:1.2rem;text-align:center;user-select:none;vertical-align:middle;white-space:nowrap;margin-top:2em;margin-bottom:2em;margin-right:auto;margin-left:auto;-webkit-border-radius:4px;-moz-border-radius:4px;-ms-border-radius:4px;box-shadow:0 3px 0 rgba(0,0,0,0.05);min-width:100px;color:#fff;background-color:#3F5BCA;border-style:none;width:100%;" >
        Ir a mis evaluaciones
      </a>
      <p class="disclaimer" style="margin-top:0;margin-right:0;margin-left:0;padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;font-size:.6em;text-align:justify;margin-bottom:10px;" >
        Estas recibiendo este correo porque perteneces a una lista de correos los cuales fueron seleccionados por “Licuadora” para el envío de las ligas correspondientes al servicio de evaluaciones del desempeño por parte de un consultor  independiente especializado para garantizar la confidencialidad y objetividad de la encuesta y sus resultados.
      </p>
      <p class="disclaimer" style="margin-top:0;margin-right:0;margin-left:0;padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;font-size:.6em;text-align:justify;margin-bottom:10px;" >
        Este correo es parte de un servicio de correo auto generado por nuestro sistema por lo que no es necesario que conteste a este correo, en caso de dudas consulte la ventana de contacto dentro del portal.
      </p>
    </div>
    <div class="footer" style="margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;" >
      <h6 style="font-family:'Open Sans',sans-serif;font-weight:300;letter-spacing:1px;margin-top:0;margin-right:0;margin-left:0;padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;font-size:.7em;text-align:center;margin-bottom:1.5em;color:#fff;" >Sistema desarrollado por 2 Geeks one Monkey ©2017</h6>
      <img class="footer-logo" src="https://qa.2geeksonemonkey.com/mailings/images/monkey-logo.png" alt="" style="margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;width:40px;" >
    </div>
</body>
</html>